version: '3'

services:
  haha_db:
    image: 'postgres:15-alpine'
    hostname: haha_db
    environment:
      - POSTGRES_DB=haha
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5435:5432"

  haha:
    container_name: haha
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - haha_db